// <auto-generated />
using System;
using Gigs.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gigs.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20251221234545_AddFestivalYear")]
    partial class AddFestivalYear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gigs.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("Gigs.Models.Festival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Festival");
                });

            modelBuilder.Entity("Gigs.Models.Gig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid?>("FestivalId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TicketCost")
                        .HasColumnType("numeric");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FestivalId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("VenueId");

                    b.ToTable("Gig");
                });

            modelBuilder.Entity("Gigs.Models.GigArtist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHeadliner")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("SetlistUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GigId");

                    b.ToTable("GigArtist");
                });

            modelBuilder.Entity("Gigs.Models.GigArtistSong", b =>
                {
                    b.Property<Guid>("GigArtistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("GigArtistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("GigArtistSong");
                });

            modelBuilder.Entity("Gigs.Models.GigAttendee", b =>
                {
                    b.Property<Guid>("GigId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("GigId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("GigAttendee");
                });

            modelBuilder.Entity("Gigs.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Gigs.Models.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Song");
                });

            modelBuilder.Entity("Gigs.Models.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Venue");
                });

            modelBuilder.Entity("Gigs.Models.Gig", b =>
                {
                    b.HasOne("Gigs.Models.Festival", "Festival")
                        .WithMany("Gigs")
                        .HasForeignKey("FestivalId");

                    b.HasOne("Gigs.Models.Venue", "Venue")
                        .WithMany("Gigs")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Festival");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Gigs.Models.GigArtist", b =>
                {
                    b.HasOne("Gigs.Models.Artist", "Artist")
                        .WithMany("Gigs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gigs.Models.Gig", "Gig")
                        .WithMany("Acts")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Gig");
                });

            modelBuilder.Entity("Gigs.Models.GigArtistSong", b =>
                {
                    b.HasOne("Gigs.Models.GigArtist", "GigArtist")
                        .WithMany("Songs")
                        .HasForeignKey("GigArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gigs.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GigArtist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Gigs.Models.GigAttendee", b =>
                {
                    b.HasOne("Gigs.Models.Gig", "Gig")
                        .WithMany("Attendees")
                        .HasForeignKey("GigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gigs.Models.Person", "Person")
                        .WithMany("Gigs")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gig");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Gigs.Models.Song", b =>
                {
                    b.HasOne("Gigs.Models.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Gigs.Models.Artist", b =>
                {
                    b.Navigation("Gigs");
                });

            modelBuilder.Entity("Gigs.Models.Festival", b =>
                {
                    b.Navigation("Gigs");
                });

            modelBuilder.Entity("Gigs.Models.Gig", b =>
                {
                    b.Navigation("Acts");

                    b.Navigation("Attendees");
                });

            modelBuilder.Entity("Gigs.Models.GigArtist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Gigs.Models.Person", b =>
                {
                    b.Navigation("Gigs");
                });

            modelBuilder.Entity("Gigs.Models.Venue", b =>
                {
                    b.Navigation("Gigs");
                });
#pragma warning restore 612, 618
        }
    }
}
